on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: publish

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
      # The logic below handles the npm publication:
      - uses:
          actions/checkout@v4
          # these if statements ensure that a publication only occurs when
          # a new release is created:
        if: ${{ steps.release.outputs.release_created }}
      - uses: pnpm/action-setup@v3
        with:
          version: 11
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org/
          cache: 'pnpm'
          node-version: 22.x
        if: ${{ steps.release.outputs.release_created }}
      - name: Run install
        run: pnpm run ci
        if: ${{ steps.release.outputs.release_created }}
      - name: Run build
        run: pnpm build
        if: ${{ steps.release.outputs.release_created }}
      - name: Run test
        run: pnpm test
        if: ${{ steps.release.outputs.release_created }}
      - name: Publish to NPM
        run: |
          # Fetch the tag name generated by release-please (e.g., v9.0.0-beta.0 or v8.0.0)
          RELEASE_TAG="${{ steps.release.outputs.tag_name }}"

          # Check if the tag contains "-beta"
          if [[ "$RELEASE_TAG" == *-beta* ]]; then
            echo "Beta release detected. Publishing to npm with --tag beta"
            pnpm publish --tag beta --access public --no-git-checks

          # (Optional) Check for other prerelease types if you use them
          elif [[ "$RELEASE_TAG" == *-alpha* ]]; then
            echo "Alpha release detected. Publishing to npm with --tag alpha"
            pnpm publish --tag alpha --access public --no-git-checks

          # If it is a standard stable release (no prerelease suffix)
          else
            echo "Stable release detected. Publishing to npm with standard latest tag"
            pnpm publish --access public --no-git-checks
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}
